version: '0.0.{build}'
before_build:
  - nuget restore
artifacts:
  - path: HttpLogger.$(APPVEYOR_BUILD_VERSION).nupkg
    name: nuget_pack
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: HttpLogger.sln
  publish_nuget: true
  publish_nuget_symbols: false
  include_nuget_references: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: XImXaAhmv7juP3N1QLgjU+V2u1+QjEXJnj3mv3U1uCjSzOa8c+LTl2KP3s/ClxhJ
  artifact: /.*\.nupkg/
  on:
    branch: master